# Digital Twin Honeynet - Banner Fetcher Configuration
# Configuration for fetching SSH banners and response patterns from production servers

# Target servers to fetch fingerprints from
target_servers:
  - hostname: production-server
    port: 22
    username: admin
    password: admin123
    timeout: 10
    description: "Primary production server"

  - hostname: backup-server
    port: 22
    username: admin
    password: admin123
    timeout: 10
    description: "Backup production server"

  # Add more servers as needed
  # - hostname: test-server
  #   port: 22
  #   username: test
  #   password: test123
  #   timeout: 10
  #   description: "Test server"

# Fetch settings
fetch_settings:
  max_attempts: 3
  delay_between_attempts: 2
  connection_timeout: 10
  auth_timeout: 30
  # Number of connection delay measurements
  delay_measurements: 5
  # Delay between measurements (seconds)
  measurement_delay: 0.5

# Output configuration
output:
  # File to save collected fingerprints
  fingerprint_file: honeypot/production_fingerprints.json
  # Banner fetcher config file
  config_file: honeypot/banner_config.yaml
  # Log file for banner fetching operations
  log_file: honeypot/banner_fetch.log
  # Backup fingerprints before overwriting
  backup_existing: true

# Authentication testing settings
auth_testing:
  # Test invalid usernames
  test_invalid_usernames: true
  invalid_usernames:
    - nonexistent
    - test
    - guest
    - admin_invalid

  # Test invalid passwords
  test_invalid_passwords: true
  invalid_passwords:
    - wrong_password
    - invalid
    - test123
    - password123

  # Test valid credentials
  test_valid_credentials: true
  # Commands to test during valid session
  test_commands:
    - "echo $PS1"
    - "whoami"
    - "hostname"
    - "pwd"
    - "invalid_command"

# Banner randomization settings
banner_randomization:
  # Enable banner randomization mode
  enabled: false
  # Alternative banners for randomization
  alternative_banners:
    - "SSH-2.0-OpenSSH_8.4p1 Ubuntu-5ubuntu1.1"
    - "SSH-2.0-OpenSSH_8.1p1 Debian-1+deb11u2"
    - "SSH-2.0-OpenSSH_8.3p1 Ubuntu-1ubuntu1"
    - "SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2"
    - "SSH-2.0-OpenSSH_8.0p1 Ubuntu-4ubuntu0.5"

  # Banner rotation settings
  rotation_interval: 0 # 0 = rotate per connection
  rotation_strategy: "random" # random, sequential, time_based

# Timing and delay settings
timing:
  # Base banner delay (seconds)
  base_delay: 0.05
  # Jitter range for randomization (±seconds)
  jitter_range: 0.02
  # Minimum delay (seconds)
  min_delay: 0.01
  # Maximum delay (seconds)
  max_delay: 0.15
  # Enable connection-specific delay variation
  connection_variation: true
  # Command execution timing simulation
  command_timing: true
  # Base command execution delay (seconds)
  base_command_delay: 0.1
  # Command execution jitter (±seconds)
  command_jitter: 0.05

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: honeypot/banner_fetch.log
  max_size: 10MB
  backup_count: 5

# Security settings
security:
  # Verify SSL certificates
  verify_ssl: true
  # Allow insecure connections (for testing)
  allow_insecure: false
  # Maximum concurrent connections
  max_concurrent_connections: 5
  # Rate limiting (requests per second)
  rate_limit: 2
