# Digital Twin Honeynet - HTTP Honeypot Configuration
# Configuration for HTTP honeypot behavior and production server mimicry

# Server configuration
server:
  host: 0.0.0.0
  port: 8080
  debug: false
  threaded: true
  # Maximum concurrent connections
  max_connections: 100
  # Connection timeout (seconds)
  timeout: 30

# Production server configuration
production_server:
  host: production-server
  port: 80
  scheme: http
  # Internal routing for legitimate requests
  internal_host: 192.168.1.100
  internal_port: 80

# Whitelist configuration for legitimate traffic
whitelist:
  enabled: true
  # IP addresses/networks to whitelist
  ips:
    - 127.0.0.1
    - 192.168.1.0/24
    - 10.0.0.0/8
    - 172.16.0.0/12
  # User agents to whitelist
  user_agents:
    - legitimate-bot
    - monitoring-agent
    - health-check
    - uptime-robot
  # Request patterns to whitelist
  patterns:
    - /health
    - /status
    - /ping
    - /favicon.ico

# Response timing configuration for stealth
response_timing:
  enabled: true
  # Base delay before sending response (seconds)
  base_delay: 0.1
  # Jitter range for randomization (±seconds)
  jitter_range: 0.05
  # Minimum delay (seconds)
  min_delay: 0.05
  # Maximum delay (seconds)
  max_delay: 0.3
  # Enable connection-specific delay variation
  connection_variation: true
  # Simulate different response times based on path
  path_based_timing:
    enabled: true
    # Slow responses for admin pages
    admin_delay_multiplier: 1.5
    # Fast responses for static files
    static_delay_multiplier: 0.5

# HTTP headers configuration to mimic production server
headers:
  # Server identification
  server: nginx/1.18.0 (Ubuntu)
  # Technology stack
  x_powered_by: PHP/7.4.3
  # Default content type
  content_type: text/html; charset=UTF-8
  # Date format for headers
  date_format: '%a, %d %b %Y %H:%M:%S GMT'
  # Additional security headers
  security_headers:
    X-Content-Type-Options: nosniff
    X-Frame-Options: SAMEORIGIN
    X-XSS-Protection: '1; mode=block'
    Strict-Transport-Security: max-age=31536000; includeSubDomains
    Content-Security-Policy: "default-src 'self'"

# Logging configuration
logging:
  enabled: true
  # Standard log file
  log_file: honeypot/http_honeypot.log
  # JSON structured log file
  json_log_file: honeypot/http_honeypot.json
  # Log level
  level: INFO
  # Log rotation settings
  rotation:
    max_size: 10MB
    backup_count: 5
  # Log specific events
  events:
    log_requests: true
    log_responses: true
    log_errors: true
    log_attacks: true
    log_whitelisted: false

# Attack detection patterns
attack_patterns:
  # SQL injection patterns
  sql_injection:
    - "union select"
    - "drop table"
    - "insert into"
    - "delete from"
    - "update set"
    - "or 1=1"
    - "or '1'='1"
    - "'; drop table"
    - "'; insert into"
  
  # XSS patterns
  xss:
    - "<script"
    - "javascript:"
    - "onload="
    - "onerror="
    - "onclick="
    - "onmouseover="
    - "alert("
    - "confirm("
    - "prompt("
  
  # Path traversal patterns
  path_traversal:
    - "../"
    - "..\\"
    - "....//"
    - "....\\\\"
    - "etc/passwd"
    - "etc/shadow"
    - "windows/system32"
    - "proc/self"
  
  # File inclusion patterns
  file_inclusion:
    - "include("
    - "require("
    - "include_once("
    - "require_once("
    - "file_get_contents("
    - "fopen("
  
  # Command injection patterns
  command_injection:
    - "; ls"
    - "; cat"
    - "; whoami"
    - "; id"
    - "| ls"
    - "| cat"
    - "`ls`"
    - "$(ls)"

# Response templates
templates:
  # Default homepage
  default_page: index.html
  # Error pages
  error_404: 404.html
  error_500: 500.html
  # Admin pages
  admin_login: admin_login.html
  admin_dashboard: admin_dashboard.html
  # Form pages
  contact_form: contact.html
  login_form: login.html

# Content generation
content:
  # Enable dynamic content generation
  dynamic: true
  # Randomize content slightly
  randomization: true
  # Include realistic timestamps
  include_timestamps: true
  # Generate realistic file sizes
  realistic_sizes: true
  # Content templates
  templates:
    welcome_message: "Welcome to our production server"
    error_message: "An error occurred while processing your request"
    maintenance_message: "Server is under maintenance"

# Integration settings
integration:
  # Integrate with existing logging pipeline
  logging_pipeline: true
  # Send alerts to monitoring system
  alerting: true
  # Integration with Cowrie logs
  cowrie_integration: true
  # Shared log format
  shared_log_format: true

# Performance settings
performance:
  # Enable request caching
  caching: false
  # Cache size limit
  cache_size: 1000
  # Cache TTL (seconds)
  cache_ttl: 300
  # Enable compression
  compression: true
  # Connection pooling
  connection_pooling: true
  # Rate limiting
  rate_limiting:
    enabled: true
    requests_per_minute: 100
    burst_size: 20

# Security settings
security:
  # Enable request validation
  request_validation: true
  # Maximum request size (bytes)
  max_request_size: 10485760  # 10MB
  # Maximum URL length
  max_url_length: 2048
  # Block suspicious user agents
  block_suspicious_ua: true
  # Suspicious user agents
  suspicious_user_agents:
    - "sqlmap"
    - "nikto"
    - "nmap"
    - "dirb"
    - "gobuster"
    - "wfuzz"
    - "burp"
    - "zap"
