# Digital Twin Honeynet - RDP Honeypot Configuration
# Configuration for RDP service emulation and production server mimicry

# Server configuration
server:
  host: 0.0.0.0
  port: 3389
  max_connections: 50
  timeout: 30
  # Enable SSL/TLS support
  ssl_enabled: true
  # SSL certificate path (optional)
  ssl_cert: ""
  ssl_key: ""

# Production server configuration
production_server:
  host: production-server
  port: 3389
  version: RDP 8.1
  build: 17763
  # Production server fingerprint
  fingerprint:
    server_name: Windows Server 2019
    version_string: RDP 8.1
    build_number: 17763
    supported_protocols: [RDP, SSL/TLS]
    encryption_levels: [Low, Medium, High]
    authentication_methods: [NTLM, Kerberos]

# Banner configuration for production mimicry
banner:
  # Server name to display
  server_name: Windows Server 2019
  # RDP version string
  version_string: RDP 8.1
  # Build number
  build_number: 17763
  # Enable banner randomization
  randomization_enabled: false
  # Alternative banners for randomization
  alternative_banners:
    - Windows Server 2016
    - Windows Server 2022
    - Windows 10 Pro
    - Windows 11 Pro
    - Windows Server 2012 R2

# Protocol configuration
protocol:
  # Supported RDP protocols
  supported_protocols:
    - RDP
    - SSL/TLS
  # Encryption levels supported
  encryption_levels:
    - Low
    - Medium
    - High
  # Authentication methods
  authentication_methods:
    - NTLM
    - Kerberos
  # Enable CredSSP
  credssp_enabled: true
  # Enable Network Level Authentication
  nla_enabled: true
  # Enable Smart Card authentication
  smart_card_enabled: false
  # Enable Remote Credential Guard
  credential_guard_enabled: false

# Response timing configuration for stealth
response_timing:
  enabled: true
  # Base delay before sending response (seconds)
  base_delay: 0.1
  # Jitter range for randomization (±seconds)
  jitter_range: 0.05
  # Minimum delay (seconds)
  min_delay: 0.05
  # Maximum delay (seconds)
  max_delay: 0.3
  # Enable connection-specific delay variation
  connection_variation: true

# Logging configuration
logging:
  enabled: true
  # Standard log file
  log_file: honeypot/rdp_honeypot.log
  # JSON structured log file
  json_log_file: honeypot/rdp_honeypot.json
  # Log level
  level: INFO
  # Log rotation settings
  rotation:
    max_size: 10MB
    backup_count: 5
  # Log specific events
  events:
    log_connections: true
    log_handshakes: true
    log_authentication_attempts: true
    log_version_requests: true
    log_errors: true

# Security settings
security:
  # Maximum request size (bytes)
  max_request_size: 1048576 # 1MB
  # Rate limiting
  rate_limiting:
    enabled: true
    # Requests per minute per IP
    requests_per_minute: 100
    # Burst size
    burst_size: 20
    # Rate limit window (seconds)
    window: 60
  # Connection limits
  connection_limits:
    max_connections_per_ip: 5
    max_failed_attempts: 10
    block_duration: 3600 # 1 hour
  # IP blacklist
  blacklist:
    enabled: true
    ips: []
    # Auto-blacklist suspicious IPs
    auto_blacklist: true
    # Suspicious patterns
    suspicious_patterns:
      - rapid_connections
      - failed_authentication
      - protocol_violations

# Performance settings
performance:
  # Enable connection pooling
  connection_pooling: true
  # Pool size
  pool_size: 10
  # Pool timeout
  pool_timeout: 30
  # Enable compression
  compression: true
  # Memory limits
  memory_limit: 100MB
  # CPU limits
  cpu_limit: 50

# Integration settings
integration:
  # Integrate with existing logging pipeline
  logging_pipeline: true
  # Send alerts to monitoring system
  alerting: true
  # Integration with other honeypots
  honeypot_integration: true
  # Shared log format
  shared_log_format: true
  # Integration with Cowrie logs
  cowrie_integration: true

# Monitoring and alerting
monitoring:
  # Enable health checks
  health_checks: true
  # Health check interval (seconds)
  health_check_interval: 30
  # Metrics collection
  metrics:
    enabled: true
    # Metrics endpoint
    endpoint: /metrics
    # Metrics format (prometheus, json)
    format: prometheus
  # Alerting
  alerting:
    enabled: false
    # Alert thresholds
    thresholds:
      # High connection rate (connections per second)
      high_connection_rate: 10
      # High failed authentication rate (percentage)
      high_failed_auth_rate: 50
      # High error rate (percentage)
      high_error_rate: 10

# Attack detection patterns
attack_patterns:
  # Brute force detection
  brute_force:
    enabled: true
    # Failed attempts threshold
    failed_attempts_threshold: 5
    # Time window (seconds)
    time_window: 300
    # Block duration (seconds)
    block_duration: 3600
  # Protocol violations
  protocol_violations:
    enabled: true
    # Invalid protocol versions
    invalid_versions: []
    # Malformed packets
    malformed_packets: true
  # Scanning detection
  scanning:
    enabled: true
    # Rapid connection attempts
    rapid_connections: true
    # Connection threshold
    connection_threshold: 10
    # Time window (seconds)
    time_window: 60
